### ISSUE TITLE
XRAY Fails to connect to external postgresql

### ISSUE THREAD

**Issue by challett** [jfrog/charts#422] opened 2019-07-22 16:40 UTC
**Is this a request for help?**:
yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm:
```
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```

K8s:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
xray

**What happened**:
When using an external postgres instance, I receive `role "username@hostname" does not exist` in the xray-server startup logs

```
[16:34:17 UTC 2019/07/22] [EROR] (jfrog.com/xray/internal/startup.InitSystem:57) Failed to ensure db schema for postgres: pq: role "username@hostname" does not exist
```

**What you expected to happen**:
Expect xray to connect to external database properly

**How to reproduce it** (as minimally and precisely as possible):
WIth a new azure postgresql db, pass the postgres url as https://username@hostname:password@hostname.postgres.database.azure.com:5432/database 

**Anything else we need to know**:
I am able to connect through psql cli using username@hostname.  I can see a role defined as username in the database, but not username@hostname.

Artifactory chart was able to connect to (a different) Azure postgresql db.

```
database=> select rolname from pg_roles;
      rolname      
-------------------
 azure_superuser
 pg_signal_backend
 azure_pg_admin
 postgres
username
```

```
Running on k8s environment
xray-server service container is starting...
Exec: /opt/jfrog/xray-server/server  
Server[16:34:16 UTC 2019/07/22] [INFO] (jfrog.com/xray/internal/startup.InitXrayServer:71) Xray xdistribution: docker
[16:34:16 UTC 2019/07/22] [INFO] (jfrog.com/xray/configs/config/secrets.LoadXraySecretFile:22) Secrets file does not exists
[16:34:16 UTC 2019/07/22] [INFO] (jfrog.com/xray/internal/dbaccess.setPostgresStatementTimeoutFromConfig:83) Setting Postgres statement timeout to 18000000
[16:34:17 UTC 2019/07/22] [INFO] (jfrog.com/xray/internal/migration/helper.ServerMigration.func1:29) Not running Migration server
[16:34:17 UTC 2019/07/22] [INFO] (jfrog.com/xray/internal/jobs.ScheduleJob:103) HeartbeatJob job listener has been triggered
[16:34:17 UTC 2019/07/22] [INFO] (jfrog.com/xray/internal/dbaccess.createTablesIfNotExist:146) Initializing db tables
[16:34:17 UTC 2019/07/22] [INFO] (jfrog.com/xray/internal/dbaccess.createComponentsConcurrentIndex:174) creating components concurrent index
[16:34:17 UTC 2019/07/22] [INFO] (jfrog.com/xray/internal/dbaccess.CreateGetChildrenFuncIfNotExist:199) Initializing get children func 
[16:34:17 UTC 2019/07/22] [EROR] (jfrog.com/xray/internal/dbaccess.CreateGetChildrenFuncIfNotExist:203) Failed to create getChildren func: pq: role "username@hostname" does not exist
[16:34:17 UTC 2019/07/22] [EROR] (jfrog.com/xray/internal/startup.InitSystem:57) Failed to ensure db schema for postgres: pq: role "username@hostname" does not exist
```

**Comment by eldada** [comment] 2019-07-23 19:23
@challett - can you please provide the command line and config used so we can try to reproduce?
Also - what Xray chart version did you use?

**Comment by challett** [comment] 2019-07-24 17:35
`helm install jfrog/xray --set "global.postgresqlUrl=postgres://username@hostname:password@hostname.postgres.database.azure.com:5432/dbname" --set "postgresql.enabled=false" --name xray --namespace xray`

I have not pinned a version, so I presume it is the latest, I re-added the jfrog repo today.

**Comment by eldada** [comment] 2019-07-25 07:41
Thanks @challett . We are looking into a potential issue with Xray internally. Will update here when we have more details.

**Comment by challett** [comment] 2019-07-25 13:04
Thank you @eldada, looking forward to hearing back.

**Comment by nimerb** [comment] 2019-07-30 13:58
@challett We have reproduce this internally and indeed Xray does not connect to the Azure PSDB out of the box and needs modification on the Azure PSDB side. 
To work around this issue please do the following in Azure:

1 - Use the admin role given by Azure that you initially connected with to PSDB (for example **challett**) - **Remember the password of this role to connect when setting up with Xray.**
2 - Create a new role named (**challett@hostname**) 
3 - In the client tab (PgAdmin for example) right click on properties of role "azure_pg_admin" and under Membership tab, add the relevant "challett@hostname"
4 - On the name of the database (postgres for example) right click and change owner to "challet@hostname"

The above steps should be enough to connect to the Azure PSDB.

**Comment by challett** [comment] 2019-07-30 21:33
Thank you for your response @nimerb 

I expected this to be the workaround, is there a ticket internally to change this? Maybe accepting a username and password similarly to how Artifactory does? 

Is the expected behavior for postgres to have the role "challett" in the db instead of "challett@hostname"?

For context I am trying to minimize required manual steps and use open service broker for azure to provision the database, so the manual workaround is not ideal.

Again thank you for the response.  I'll open a ticket for Xray directly if you need me to.

**Comment by nimerb** [comment] 2019-07-31 07:11
Regarding the same handling as Artifactory (username and password), this is not applicable at the moment when using Xray. 
For some reason Azure would require you to have a role "challetr" with the password configured and user "challett@hostname" and in the role "azure_pg_admin" you should add "challett@hostname" to it's Membership.
P.S: All the required steps can be done one time manually and then extract all the queries ran in the background and you can run all the queries without any manual modification.

**Comment by eldada** [comment] 2019-07-31 08:36
We have plans to simplify the DB connection setup in the next Xray major release. This will allow for an easier to manage the DB configuration details. ETA is in a few months.

**Comment by challett** [comment] 2019-07-31 12:50
Okay thank you @eldada .  Just want to point out that I do not believe it is Azure that has this requirement, but likely the way that xray is handling the connection, since other applications do not require this modification.

Thank you for your input.  Is there a ticket I can follow for this enhancement in xray?

**Comment by eldada** [comment] 2019-08-01 05:56
No. Sorry. This is managed internally. You can wait for Xray 3.0 to be released in a few months. 
https://bintray.com/jfrog/ is where we publish the releases, and you can watch them.

**Comment by challett** [comment] 2019-08-01 12:15
That's fine I have a release target to wait for now.  

Thank you very much for your help, feel free to close the ticket as you see fit.

**Closed** 2019-08-01 12:16 UTC

**Comment by jaygridley** [comment] 2020-03-31 20:00
Hello, I've started the deployment of Xray 3.2.3 and this issue is still present. Are there any plans to fix it?

**Comment by JfrogPrasanna** [comment] 2020-04-01 06:27
@jaygridley refer this  issue which was  closed recently - https://github.com/jfrog/charts/issues/711 
you need to pass database.user and  database.password separately and not in the url. Let me know if that works.

**Comment by jaygridley** [comment] 2020-04-03 10:20
@JfrogPrasanna This does not help for our use-case. As Azure PostgreSQL requires username with server name - user@server-name. I think that Xray does not recognize that correctly. As a workaround I have to specify username in URL like this `postgres://<server>:<port>/<dbname>?user=urlencode(<username>)&password=urlencode(<password>)`

**Comment by fl-max** [comment] 2021-03-26 17:48
Seems the first error that you get:
```sh
Database ping failed with error dial tcp <pod_ip>:5432: connect: connection refused
Database connection check failed <nil>
```

Is a result of line# 2980 in installerCommon.sh:
`${productHome}/app/bin/diagnostics/diagnosticsUtil jfrog database-status "{{shared.database.url}}" "{{shared.database.type:${databaseLabel}}}" "{{shared.database.username:${databaseUsername}}}" "{{shared.database.password}}" 2>&1 || true`

It expects the database to be defined in YAML and does not check the `JF_SHARED_DATABASE_*` Env Vars.

However, even with setting these in the System.yaml, I still get the following error:
`2021-03-26T17:31:46.726Z [jfxr ] [ERROR] [ ] [crypto_service:148 ] [main ] No user / password found`

So I think this is still an issue.

**Comment by FalconerTC** [comment] 2021-05-25 19:45
Any update on this? I'm seeing the same thing as fl-max when attempting to connect to Google Cloud SQL. The `JF_SHARED_DATABASE` envs are being ignored

**Comment by chukka** [comment] 2021-07-14 04:51
we have added support using [actualUsername](https://github.com/jfrog/charts/blob/master/stable/xray/values.yaml#L265) in systemYaml , please refer https://www.jfrog.com/confluence/display/JFROG/Xray+System+YAML

**Comment by fl-max** [comment] 2021-07-19 14:39
@chukka `actualUsername` has been there for some time. Are you saying that you've added this to the `installerCommon.sh` script? can you post or link to the relevant line I mentioned [here](https://github.com/jfrog/charts/issues/422#issuecomment-808407479) because I don't think this fixes the issue.

**Comment by bery** [comment] 2021-09-14 08:43
The same issue appears to be present for artifactory-ha setup. Any plans on fixing it?
