### ISSUE TITLE
Permissions issue when trying to import a custom certificate in JFMC/Distribution

### ISSUE THREAD

**Issue by danielezer** [jfrog/charts#648] opened 2020-02-18 14:41 UTC
**Is this a request for help?**:
NO
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

I have deployed this and I was able to mount my certificate into the Distribution container, but looking at the logs seems that keytool is not adding the certificate to cacerts. Here is the output from the command logs (from kubectl logs from the Distribution container):

Running custom Distribution preStartCommand command
Warning: use -cacerts option to access cacerts keystore
Certificate was added to keystore
keytool error: java.io.FileNotFoundException: /java/jdk-11.0.2+9/lib/security/cacerts (Permission denied)
I tried doing a docker exec as root into the container to run the command manually, but I got the same error. Taking a look at the folder, this is the ls output:

root@distribution-0:/java/jdk-11.0.2+9/lib/security# ls -la
total 356
drwxr-xr-x    2 500      500             98 Jan  1  1970 .
drwxr-xr-x    6 500      500           4096 Jan  1  1970 ..
-rw-r--r--    1 500      500           1253 Jan  1  1970 blacklisted.certs
-rw-r--r--    1 500      500         102883 Jan  1  1970 cacerts
-rw-r--r--    1 500      500           8815 Jan  1  1970 default.policy
-rw-r--r--    1 500      500         234959 Jan  1  1970 public_suffix_list.dat
From the dates, looks like the file wasn't modified. So the file exists but for some reason not even root can modify it. Have any clue what I'm missing?

I used the same command that I used for the other services, as suggested in your template:

/java/jdk-11.0.2+9/bin/keytool -importcert -keystore /java/jdk-11.0.2+9/lib/security/cacerts -storepass changeit -file <mount-location> -alias <alias> -noprompt
And logs show that SSL handshake didn't succeed:

2020-02-14 22:40:15,214 [http-nio-8080-exec-7] [ERROR] (o.j.b.d.s.p.t.EdgeNodesServiceImpl:104) Failed getting platform services from Mission Control
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Side note
Does it make sense to also implement these in the distributor container? All our Artifactory nodes will have certificates issued from the same private CA. Asking because I noticed you guys also include a preStartCommand with the keytool example there, but I no see custom volume or mount options. Not sure if the distributor container interacts directly with the services. 🤔

Thanks in advance.

ref #637

**Comment by erick-duran** [comment] 2020-02-18 14:46
Thank you @danielezer, can you please let me know as soon as this is fixed? This is blocking us from making our production deployment. Any suggested workaround?

**Comment by danielezer** [comment] 2020-02-18 14:59
@erick-duran it would be great if you could upvote this issue and add a comment saying that - https://www.jfrog.com/jira/browse/INST-566. This

**Comment by danielezer** [comment] 2020-02-18 15:02
@erick-duran Sure. I'll keep this issue updated.

**Comment by erick-duran** [comment] 2020-02-20 01:43
@danielezer,
FYI, got the same behavior in the `distributor` container:
```bash
$ kubectl logs pod/distribution-0 -c distributor
Running Distributor custom preStartCommand command
Warning: use -cacerts option to access cacerts keystore
Certificate was added to keystore
keytool error: java.io.FileNotFoundException: /java/jdk-11.0.2+9/lib/security/cacerts (Permission denied)
```

And permissions are also `500`.

**Comment by danielezer** [comment] 2020-02-20 14:09
Thanks @erick-duran, good to know

**Comment by erick-duran** [comment] 2020-02-27 01:22
Any updates on this?

**Comment by eldada** [comment] 2020-02-27 07:55
Hi @erick-duran .
We identified the root cause for this is a bug in our Docker images and are now actively working on a fix.

**Comment by erick-duran** [comment] 2020-03-17 18:31
Any updates on this?

**Comment by chukka** [comment] 2020-03-24 12:00
Thanks for patience ! we have a internal fix ready and will be rolled out  next week , I will provide an update when its ready

**Comment by chukka** [comment] 2020-04-06 07:18
@erick-duran distribution-3.6.1 released with appropriate  fix for distribution , Can you please try this chart and share the feedback 
Closing this issue .

**Closed by chukka** 2020-04-06 07:18 UTC
Labels: bug
