### ISSUE TITLE
Bug: integer values are rendered as scientific notations

### ISSUE THREAD

**Issue by lukasmrtvy** [jfrog/charts#1466] opened 2021-07-07 20:40 UTC
**Version of Helm and Kubernetes**:
helm 3.2.4
kubernetes 1.18

**Which chart**:
artifactory 107.21.3

**What happened**:
Default values ( azureBlob ) for https://github.com/jfrog/charts/blob/master/stable/artifactory/values.yaml#L871-L872 are probably rendered as scientific notation.
For example `multiPartLimit` which has default value `100000000` is rendered as `1e+08`, that breaks artifactory, see attached stacktrace. 

L871-L872 should be probably fixed with: 
```
<multiPartLimit>{{ int64 .Values.artifactory.persistence.azureBlob.multiPartLimit | quote }}</multiPartLimit>
<multipartElementSize>{{ int64 .Values.artifactory.persistence.azureBlob.multipartElementSize | quote }}</multipartElementSize>
```

**What you expected to happen**:
`multiPartLimit` ( and others ) is rendered as string ( `100000000` )

**How to reproduce it** (as minimally and precisely as possible):
```
   artifactory: 
      persistence:
        enabled: true
        storageClassName: retain
        size: 5000Gi 
        type: azure-blob 
        azureBlob:
          accountName: xxxx
          accountKey: xxxx
          containerName: artifactory
```

**Anything else we need to know**:
```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'binaryServiceImpl': Invocation of init method failed; nested exception is java.lang.NumberFormatException: For input string: "1e+08"
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:415)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1307)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.inject(AutowiredAnnotationBeanPostProcessor.java:715)
	... 72 common frames omitted
Caused by: java.lang.NumberFormatException: For input string: "1e+08"
```
Related: https://github.com/helm/helm/pull/3599

Workaround:
Is possible to hardcode values directly to `artifactory.persistence.binarystoreXml`

**Comment by ToniCipriani** [comment] 2021-08-06 19:08
Seeing the same issue here. Also noticed that Artifactory's documentation does not refer to these values at all for Azure Storage:

https://www.jfrog.com/confluence/display/JFROG/Configuring+the+Filestore#ConfiguringtheFilestore-AzureBlobStorageBinaryProvider

**Comment by chukka** [comment] 2021-09-06 17:35
@lukasmrtvy will be fixed with 7.27.x release ( ETA - end of this month)

**Comment by chukka** [comment] 2021-09-30 16:38
Fixed in #1509

**Comment by chukka** [comment] 2021-09-30 16:39
@lukasmrtvy @ToniCipriani Please verify on the latest chart

**Closed by chukka** 2021-09-30 16:38 UTC
Labels: bug

**Comment by chukka** [comment] 2022-09-13 02:19
@wokoman can you share your values.yaml file ?

@lukasmrtvy @ToniCipriani  did you get a chance to try post fixing this , Appreciate if you can confirm on this ?

**Comment by wokoman** [comment] 2022-09-13 05:53
@chukka Ended fixing it myself.

Thing was, that Artifactory simply kept corrupted `binaryStore.xml` and did not overwritten it with a new one from secret. I had to shell into the pod and remove the file from `/opt/jfrog/artifactory/var/etc/artifactory`. Upon restart, Artifactory created a fresh one with correct values.

I used 7.27.15 for this. So leaving this here for reference.

**Comment by dennisheller-nokia** [comment] 2022-09-13 06:02
I fixed it long time ago by adding to values.yaml
```
artifactory:
  copyOnEveryStartup:
    - source: /artifactory_bootstrap/binarystore.xml
      target: etc/artifactory/
```

**Comment by chukka** [comment] 2022-09-13 06:27
@wokoman @dennisheller-nokia  Thanks for sharing , By design `binaryStore.xml` is not overridden unless you use `copyOnEveryStartup`  feature. This will change in upcoming 7.45.x release .

Heads up - There are big binarystore changes coming up in 7.45.x release (please check changelog for all changes)   , stay tuned :)
