### ISSUE TITLE
Cannot connect to the database when using a custom db-user on a secret

### ISSUE THREAD

**Issue by esg-dlelis** [jfrog/charts#586] opened 2019-12-11 19:57 UTC
BUG REPORT

**Version of Helm and Kubernetes**:
k8s: 1.14.7
Helm: v3.0.1

**Which chart**:
artifactory-jcr
version" 6.16.0

**What happened**:
When I try to set the database.secrets values to get my db-user and db-password from a secret, the artifactory instalation cannot connect to my external database.

If I try to use database.user and database.password it works fine. 

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
Install it with an external postgres database and try to put the db-user and db-password on a secret.
Set the database.secrets values to match your database credentials.

**Anything else we need to know**:
All of my logs are attached to the request, a set from when it works, and a set from when it doesnt't.
If you look at my logs you'll see that it sets the DB_USER env variable correctly: 
2019-12-11 18:47:15  [352 entrypoint-artifactory.sh] Setting DB_USER to artifactory-jcr

But when it tries to create a connection pool it uses the artifactory user:
SEVERE: Unable to create initial connections of pool.
org.postgresql.util.PSQLException: FATAL: password authentication
[artifactory-pod-install-problem.log](https://github.com/jfrog/charts/files/3952284/artifactory-pod-install-problem.log)
[artifactory-pod-install-working.log](https://github.com/jfrog/charts/files/3952285/artifactory-pod-install-working.log)

[masterkey-startup-not-set.zip](https://github.com/jfrog/charts/files/3952288/masterkey-startup-not-set.zip)

 failed for user "artifactory"

**Comment by esg-dlelis** [comment] 2019-12-11 20:26
Additional info, I changed the db-user from artifactory-jcr to artifactory, still doesn't work

**Comment by danielezer** [comment] 2020-01-26 09:54
Thanks for reporting this @esg-dlelis, I can reproduce this issue. I will look into it shortly

**Comment by danielezer** [comment] 2020-01-26 13:31
@esg-dlelis I'm pretty sure I found the issue. 
The issue is actually this error message:
```
2019-12-11 18:47:15  [352 entrypoint-artifactory.sh] Setting DB_USER to artifactory-jcr

sed: unmatched '/'
2019-12-11 18:47:15  [356 entrypoint-artifactory.sh] Setting DB_PASSWORD to **********
sed: unmatched '/'
```

This happens because there's trailing whitespace in the value of the environment variables `DB_USER` and `DB_PASSWORD`.
For example:
When I follow this procedure to create a secret with the database username and password:
```
➜  artifactory git:(master) ✗ echo artifactory-password > db-password
➜  artifactory git:(master) ✗ echo artifactory-test > db-user
➜  artifactory git:(master) ✗ kubectl create secret generic database-password --from-file=db-password --namespace artifactory
secret/database-password created
➜  artifactory git:(master) ✗ kubectl create secret generic database-user --from-file=db-user --namespace artifactory
secret/database-user created
```
and then deploy artifactory using helm, I see the same error message you saw.
When I `exec` into the container like so:
```
kubectl exec -it -n artifactory artifactory-artifactory-0 bash
```

I can see that a whitespace was added to the value of the `DB_USER` and `DB_PASSWORD` environment variables:
```
artifactory@artifactory-artifactory-0:/$ echo ${DB_USER}addition-to-see-whitespace
artifactory-test addition-to-see-whitespace
artifactory@artifactory-artifactory-0:/$ echo ${DB_PASSWORD}addition-to-see-whitespace
artifactory-password addition-to-see-whitespace
```
Now, if I run the actual sed command that issues the warning we saw before I get the same result:
```
artifactory@artifactory-artifactory-0:/$ export DB_PROPS=/var/opt/jfrog/artifactory/etc/db.properties
artifactory@artifactory-artifactory-0:/$ sed -i "s/password=.*/password=$DB_PASSWORD/g" ${DB_PROPS}
sed: unmatched '/'
```

Now, if I follow the same procedure to create a secret from the beginning, but this time I make sure that there's no whitespace at the end of the file I stored my secret in:
```
bash-3.2$ echo -n artifactory-test > db-user
bash-3.2$ cat db-user
artifactory-testbash-3.2$
bash-3.2$
bash-3.2$ echo -n artifactory-password > db-password
bash-3.2$ cat db-password
artifactory-passwordbash-3.2$
bash-3.2$
bash-3.2$ kubectl create secret generic database-user --from-file=db-user --namespace artifactory
secret/database-user created
bash-3.2$ kubectl create secret generic database-password --from-file=db-password --namespace artifactory
secret/database-password created
```
Notice that this time I don't have a newline at the end of the file, and because of that, when I try to deploy Artifactory using helm again, it works as expected.

**Comment by danielezer** [comment] 2020-01-30 09:52
@esg-dlelis I'm closing this issue, this should fix your issue. Let me know it doesn't get resolved and I'll re-open the issue

**Closed by danielezer** 2020-01-30 09:52 UTC
