### ISSUE TITLE
Add support to allow the import of SSL certs to Xray Helm chart

### ISSUE THREAD

**Issue by sanjeevkarani** [jfrog/charts#891] opened 2020-05-14 05:43 UTC
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature Request

**Version of Helm and Kubernetes**:

**Which chart**:
Xray

**What happened**:
Current behavior requires unsecured communication with Artifactory

**What you expected to happen**:
Secured communication with Artifactory

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by evannorstrand** [comment] 2020-06-29 18:48
Duplicate of #891

If your a paying customer, please submit a support ticket directly to JFROG and reference #891. The more paying customers complain the faster this will be fixed.

**Comment by chukka** [comment] 2020-07-21 12:16
@sanjeevkarani please check [artifactory](https://github.com/jfrog/charts/blob/master/stable/artifactory/README.md#establishing-tls-and-adding-certificates) and [xray](https://github.com/jfrog/charts/blob/master/stable/xray/README.md#establishing-tls-and-adding-certificates) changes. 

Please try below charts and share feedback

artifactory-10.0.6
artifactory-ha-3.0.6
xray-4.1.2

**Closed by chukka** 2020-07-21 12:17 UTC
Labels: xray
