### ISSUE TITLE
artifactory-ha cannot find join key during migration from 6.x to 7.x

### ISSUE THREAD

**Issue by hichamuntitled** [jfrog/charts#865] opened 2020-04-27 10:29 UTC
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT 

**Version of Helm and Kubernetes**:
helm: v2.11.0
Kubernetes: 1.14 (eks)

**Which chart**: starting from 2.0.0 till 2.4.4

**What happened**:
I am trying to migrate artifactory-ha from version 6.16 (chart 1.3.6) to 7.x.x. (chart 2.x.x)
It block on the initConainer : migration-artifactory-ha, on the logs I see : 
```
[main] - Bootstrap joinKey found in [/opt/jfrog/artifactory/var/bootstrap/access/etc/security/join.key:]. Deleting original
```
then 
```
[INFO ] [7751b16fcf75824 ] [security_keys.go:128          ] [main                ] - Cluster join: Join key is missing. Pending for 15 seconds with 2m0s timeout
.
.
.
 [ERROR] [b8eb8c79386c4388] [tifactoryHomeConfigListener:59] [ocalhost-startStop-2] - Failed initializing Home. Failed to init db properties:
[ERROR] [b8eb8c79386c4388] [actoryContextConfigListener:82] [ocalhost-startStop-2] - Failed initializing Artifactory context: Artifactory home not initialized.
[SEVERE] [                ] [org.apache.catalina.core.StandardContext] [org.apache.catalina.core.StandardContext startInternal] - One or more listeners failed to start. Full details will be found in the appropriate container log file
[SEVERE] [                ] [org.apache.catalina.core.StandardContext] [org.apache.catalina.core.StandardContext startInternal] - Context [/artifactory] startup failed due to previous errors
[INFO ] [7751b16fcf75824 ] [security_keys.go:128          ] [main                ] - Cluster join: Join key is missing. Pending for 55 seconds with 2m0s timeout

[ERROR] [606175f05af5d63d] [o.s.b.SpringApplication:822   ] [ocalhost-startStop-1] - Application run failed
org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.jersey.JerseyAutoConfiguration': Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jerseyConfig' defined in URL [jar:file:/opt/jfrog/artifactory/app/artifactory/tomcat/webapps/access/WEB-INF/lib/access-application-5.3.9.jar!/org/jfrog/access/rest/config/JerseyConfig.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'httpServiceImpl' defined in URL [jar:file:/opt/jfrog/artifactory/app/artifactory/tomcat/webapps/access/WEB-INF/lib/access-server-core-5.3.9.jar!/org/jfrog/access/server/service/http/HttpServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'internalConfigurationServiceImpl' defined in URL [jar:file:/opt/jfrog/artifactory/app/artifactory/tomcat/webapps/access/WEB-INF/lib/access-server-core-5.3.9.jar!/org/jfrog/access/server/service/configuration/InternalConfigurationServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'accessConfigurationStorageServiceImpl' defined in URL [jar:file:/opt/jfrog/artifactory/app/artifactory/tomcat/webapps/access/WEB-INF/lib/access-server-core-5.3.9.jar!/org/jfrog/access/server/service/db/AccessConfigurationStorageServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'accessConfigsDao' defined in URL [jar:file:/opt/jfrog/artifactory/app/artifactory/tomcat/webapps/access/WEB-INF/lib/access-server-core-5.3.9.jar!/org/jfrog/access/server/db/dao/AccessConfigsDao.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'accessJdbcHelperImpl' defined in URL [jar:file:/opt/jfrog/artifactory/app/artifactory/tomcat/webapps/access/WEB-INF/lib/access-server-core-5.3.9.jar!/org/jfrog/access/server/db/util/AccessJdbcHelperImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dbProperties' defined in class path resource [org/jfrog/access/server/db/spring/DbConfigFactory.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jfrog.storage.DbProperties]: Factory method 'dbProperties' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'internalAccessHome' defined in class path resource [org/jfrog/access/server/home/InternalAccessHomeConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jfrog.access.server.home.InternalAccessHome]: Factory method 'internalAccessHome' threw exception; nested exception is java.lang.IllegalStateException: Failed to init db properties:
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:156)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:743)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:390)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
        at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:151)
        at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:131)
        at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:91)
        at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:172)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5154)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
        at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:614)
        at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1823)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.jersey.JerseyAutoConfiguration': Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jerseyConfig' defined in URL [jar:file:/opt/jfrog/artifactory/app/artifactory/tomcat/webapps/access/WEB-INF/lib/access-application-5.3.9.jar!/org/jfrog/access/rest/config/JerseyConfig.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'httpServiceImpl' defined in URL [jar:file:/opt/jfrog/artifactory/app/artifactory/tomcat/webapps/access/WEB-INF/lib/access-server-core-5.3.9.jar!/org/jfrog/access/server/service/http/HttpServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'internalConfigurationServiceImpl' defined in URL [jar:file:/opt/jfrog/artifactory/app/artifactory/tomcat/webapps/access/WEB-INF/lib/access-server-core-5.3.9.jar!/org/jfrog/access/server/service/configuration/InternalConfigurationServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'accessConfigurationStorageServiceImpl' defined in URL [jar:file:/opt/jfrog/artifactory/app/artifactory/tomcat/webapps/access/WEB-INF/lib/access-server-core-5.3.9.jar!/org/jfrog/access/server/service/db/AccessConfigurationStorageServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'accessConfigsDao' defined in URL [jar:file:/opt/jfrog/artifactory/app/artifactory/tomcat/webapps/access/WEB-INF/lib/access-server-core-5.3.9.jar!/org/jfrog/access/server/db/dao/AccessConfigsDao.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'accessJdbcHelperImpl' defined in URL [jar:file:/opt/jfrog/artifactory/app/artifactory/tomcat/webapps/access/WEB-INF/lib/access-server-core-5.3.9.jar!/org/jfrog/access/server/db/util/AccessJdbcHelperImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dbProperties' defined in class path resource [org/jfrog/access/server/db/spring/DbConfigFactory.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jfrog.storage.DbProperties]: Factory method 'dbProperties' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'internalAccessHome' defined in class path resource [org/jfrog/access/server/home/InternalAccessHomeConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jfrog.access.server.home.InternalAccessHome]: Factory method 'internalAccessHome' threw exception; nested exception is java.lang.IllegalStateException: Failed to init db properties:
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)

.
.
.
[FATAL] [2f98cd3358259ccf] [bootstrap.go:92               ] [main                ] - Cluster join: Failed resolving join key: failed resolving 'shared.security.joinKey' key; file does not exist: /opt/jfrog/artifactory/var/etc/security/join.key
Waiting for Artifactory to start --- sleeping for 10 seconds
Waiting for Artifactory to start --- sleeping for 10 seconds
Waiting for Artifactory to start --- sleeping for 10 seconds

```
and to be clear, in my values files, i've commented the masterKey. then I added a join key.

**What you expected to happen**:
migration to be OK.

**How to reproduce it** (as minimally and precisely as possible):

1. install chart 1.3.6 with a masterKey
2. edit values file, remove masterKey declaration and add a joinKey
3. install chart 2.4.4

**Anything else we need to know**:
why artifactory found the join key in `/opt/jfrog/artifactory/var/bootstrap/access/etc/security/join.key` then deletes it ?
Why join key and master key are written to different paths : https://github.com/jfrog/charts/blob/master/stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml#L167 ?

I've seen #674 but it does not help

**Comment by hichamuntitled** [comment] 2020-04-27 13:03
While it was waiting 
```
Waiting for Artifactory to start --- sleeping for 10 seconds
Waiting for Artifactory to start --- sleeping for 10 seconds
Waiting for Artifactory to start --- sleeping for 10 seconds
```
I get connected to the container via `kubectl exec -ti artifactory-ha-primary-0 -c migration-artifactory-ha -- bash` then I ran 
```
cp /opt/jfrog/artifactory/var/bootstrap/access/etc/security/join.key /opt/jfrog/artifactory/var/etc/security/join.key
```
so now in the logs I see 
```
[INFO ] [417d3d02b1dcdca6] [join_executor.go:148          ] [main                ] - Cluster join: Retry 10: Service registry ping failed, will retry. Error: Could not parse error from service registry, status code: 404, raw body: <!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> &#47;access&#47;api&#47;v1&#47;system&#47;ping</p><p><b>Description</b> The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.</p><hr class="line" /><h3>Apache Tomcat/8.5.41</h3></body></html>
Waiting for Artifactory to start --- sleeping for 10 seconds
```

**Comment by mhamaydeh** [comment] 2020-04-27 14:15
@hichamuntitled i faced this before , 
https://github.com/jfrog/charts/issues/677

**Comment by chukka** [comment] 2020-04-27 14:29
@hichamuntitled  masterKey and joinKey  are two different keys. Please refer documentation -[here](https://github.com/jfrog/charts/tree/master/stable/artifactory-ha#special-upgrade-notes-1) for more info. 

Also, JoinKey can be passed as shown below
```
# Create a key
export JOIN_KEY=$(openssl rand -hex 32)
echo ${JOIN_KEY}

# Pass the created join key to helm
helm upgrade --install artifactory-ha --set artifactory.joinKey=${JOIN_KEY} --namespace artifactory-ha jfrog/artifactory-ha



```

**Comment by hichamuntitled** [comment] 2020-04-27 14:35
@mhamaydeh already tested but not working :/ 

@chukka I've tested every possible solution mentioned in the documentation. My problem is about join Key, I've generated it via openssl command, I tried to : 
- pass it to the upgrade command `--set artifactory.joinKey=${JOIN_KEY}`
- adding it to the values files
- using a secret
and all of them are not working

**Comment by chukka** [comment] 2020-04-27 14:40
@hichamuntitled Can you share your helm install /upgrade command appending` --debug --dry-run`  to reproduce this issue?
Also, share the values.yaml if you are passing  via values.yaml file

**Comment by hichamuntitled** [comment] 2020-04-27 15:03
the command used
```
helm upgrade artifactory-ha -f values-test.yaml --install --namespace my-namespace --tiller-namespace my-tiller-nameespace --version 2.4.4 jfrog/artifactory-ha --debug --dry-run
```
here's ma values-test.yaml file [values-test.yaml.txt](https://github.com/jfrog/charts/files/4540389/values-test.yaml.txt) 
and here's the output [debug--dry-run.log](https://github.com/jfrog/charts/files/4540395/debug--dry-run.log)

**Comment by chukka** [comment] 2020-04-27 16:15
Can you check the  value of joinKey value from secret that you used `arti-join-key`
`kubectl get secret --namespace my-namespace arti-join-key -o jsonpath="{.data.join-key}" | base64 --decode`

**Comment by hichamuntitled** [comment] 2020-04-27 16:42
Here's the output : `87c26c05611cc9ccba503b69a3c54862fccf1634deecaff8e3262cbe89b2e47b`

**Comment by chukka** [comment] 2020-05-05 07:31
@hichamuntitled  Sorry for delayed response .Looks like you didn't pass maskerKey which is mandatory for HA setup , please refer [here](https://github.com/jfrog/charts/blob/master/stable/artifactory-ha/README.md#installing-the-chart)  . Please try and let us know the feedback

**Comment by hichamuntitled** [comment] 2020-05-05 09:11
@chukka I didn't pass the master key because it's a migration from 6.x to 7.x
reference to your comment [here](https://github.com/jfrog/charts/issues/677#issuecomment-602145713)

**Comment by chukka** [comment] 2020-06-03 04:16
@hichamuntitled Is this still an issue ? If not please close this issue . Can you try upgrading to latest version - 2.5.0 (which has fixes + improvements

**Comment by chukka** [comment] 2020-06-05 16:59
@hichamuntitled  Marking this issue as closed, Feel free to reopen if it doesn't work with latest charts

**Closed by chukka** 2020-06-05 16:59 UTC
Labels: artifactory, question

**Comment by hichamuntitled** [comment] 2020-07-13 13:16
Hello, Upgrading to the last version did not solve the problem.
The only workaround was to delete the master key / fingerprint from database.

**Comment by chukka** [comment] 2020-07-14 04:53
@hichamuntitled  can you please provide reproducible steps , also share 6.x and 7.x chart versions along with values used

**Comment by skreddy6673** [comment] 2020-11-04 21:02
@chukka 
Hi Ram,
I just started the v7.9.0 upgrade process from v6.18.1 and ran into same error.
In v6.18.1 we have the masterkey so i didn't do any changes to it. When ran the helm upgrade command it gave me following error message
```
Warning  FailedCreate  48s (x28 over 18m)  statefulset-controller  create Pod artifactory-ha-dev-artifactory-ha-member-0 in StatefulSet artifactory-ha-dev-artifactory-ha-member failed error: Pod "artifactory-ha-dev-artifactory-ha-member-0" is invalid: spec.initContainers[2].env[0].valueFrom.secretKeyRef.name: Invalid value: "map[datakey:master-key secret:artifactory-ha-dev]": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```
That's because our master-key have capital letters in it. Then i updated the master-key (Which i shouldn't have done) to all lower case and the did an helm upgrade command. 
Now my pod got stuck in Initialization state.
When i looked at the migration container logs i found following error,
```
panic: Cluster join: Failed resolving join key: failed resolving 'shared.security.joinKey' key; file does not exist: /opt/jfrog/artifactory/var/etc/security/join.key
```

That's because we didn't have join-key in v6.18.1 and i didn't add it explicitly in v7.9.0 values file. After seeing the error message i added Join-key to the secrets and values file.
Then i found this issue page and read that master-key shouldn't be changed, so i reverted the master-key value and did an helm upgrade. But still seeing the same error message about Join key as posted above.

Artifactory: Upgrade from v6.18.1 to v7.9.0
Helm: v2
Kube: v1.17

**Comment by chukka** [comment] 2020-11-05 14:41
Hi @skreddy6673 ,

Can you share the chart version you are trying and provide reproducible steps (helm commands and values.yaml)

**Comment by skreddy6673** [comment] 2020-11-05 18:13
@chukka 
Thanks for your reply.
I'm using chart version of 4.2.0
I didn't add "driver" under database and it caused the issues. Adding the driver helped pass these issues.

Now i got stuck due to xray version incompatibility, we are using xray of version  2.11.4 and chart version of 1.3.8. Have to upgrade that.

**Comment by skreddy6673** [comment] 2020-11-05 20:44
@chukka Do we need to upgrade xray to v3.x before Artifctory upgrade or during Artifactory Upgrade or After Artifactory upgrade.

**Comment by chukka** [comment] 2020-11-09 11:20
@skreddy6673 Once artifactory is upgraded to 7.x , Xray needs to be upgraded from 2.x to 3.x

**Comment by lverba** [comment] 2020-11-12 07:26
@chukka I also tested migration from v6.18.0 to latest, same facing the problems with join key:
`
env|grep JOIN
JOIN_KEY=25d3e449e7d9d240f356d62560c60a85c07ccc01f307e6a66df6c9a126da941e

helm2 upgrade artifactory-tmp --set artifactory.joinKey=${JOIN_KEY} --namespace artifactory-tmp jfrog/artifactory --values artifactory-tmp-new.yml`

`- Cluster join: Failed resolving join key: failed resolving 'shared.security.joinKey' key; file does not exist: /opt/jfrog/artifactory/var/etc/security/join.key`

and migration stops on that moment :(

**Comment by skreddy6673** [comment] 2020-11-12 13:57
@lverba My observation while upgrading from v6.18 to v7.x is you need to add the followig
1) Master-Key
2) Join-Key
3) Enable Migration
4) Add `Driver` under database.

If possible can you share the values file by masking the sensitive data and Helm chart version.

**Comment by skreddy6673** [comment] 2020-11-12 16:12
> @skreddy6673 Once artifactory is upgraded to 7.x , Xray needs to be upgraded from 2.x to 3.x

We are in xray chart version of 1.3.8, so when i want to upgrade to latest chart version, can i upgrade directly to latest or do i need to via incremental process like upgrade to chart version of 2.x and then upgrade to chart version of 3.x and then upgrade to chat version of 6.x(latest)?

**Comment by lverba** [comment] 2020-11-12 18:58
@skreddy6673 tnx for reply!

1. I did not pass master key at all, i remove master key from secrets before upgrade
2. join key i create new and pass it with upgrade command
3. This is done
4. Also done

So, I'm just testing migration on test cluster, first, I'm running fresh install, but with database from current 6.18 artifactory with this values:

helm2 install --name artifactory-tmp --namespace artifactory-tmp jfrog/artifactory --values artifactory-tmp-old.yml --version 8.1.2
before install I have secret with database credentials, licence and bootstrap.creds.

Here is my artifactory-tmp-old.yml file:
```
artifactory:
  name: artifactory-tmp
  image:
    repository: docker.bintray.io/jfrog/artifactory-pro
    version: 6.18.0
    pullPolicy: IfNotPresent

  license:
    secret: artifactory-license
    dataKey: license

  accessAdmin:
    secret: artifactory-access-admin
    dataKey: bootstrap.creds

  persistence:
    enabled: true
    size: 500Gi
    mountPath: /var/opt/jfrog/artifactory

postgresql:
  enabled: false

database:
  type: postgresql
  secrets:
    url:
      name: artifactory-rds
      key: url
    user:
      name: artifactory-rds
      key: user
    password:
      name: artifactory-rds
      key: password

nginx:
  enabled: false

ingress:
  enabled: true
  hosts:
    - artifactory-tmp.domain.com
  annotations:
    custom.nginx.org/extra-server-names: >-
      ~(?<repo>.+)\.artifactory-tmp.domain.com
    nginx.org/server-snippets: |
      if ($http_x_forwarded_proto = '') {
          set $http_x_forwarded_proto  $scheme;
      }

      rewrite ^/$ /artifactory/webapp/ redirect;
      rewrite ^/artifactory/?(/webapp)?$ /artifactory/webapp/ redirect;
      rewrite ^/(v1|v2)/(.*) /artifactory/api/docker/$repo/$1/$2;

      chunked_transfer_encoding on;
      client_max_body_size 0;

      location /artifactory/ {
          add_header 'Access-Control-Allow-Origin' 'localhost:*';
          add_header 'Access-Control-Allow-Methods' 'GET';
          add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,X-JFrog-Art-Api';
          proxy_read_timeout  2400s;
          proxy_pass_header   Server;
          proxy_cookie_path   ~*^/.* /;
          if ( $request_uri ~ ^/artifactory/(.*)$ ) {
              proxy_pass          http://artifactory-tmp-artifactory-tmp-artifactory--artifactory-tmp-artifactory-8081/artifactory/$1;
          }
          proxy_pass          http://artifactory-tmp-artifactory-tmp-artifactory--artifactory-tmp-artifactory-8081/artifactory/;
          proxy_set_header    X-Forwarded-Port  $server_port;
          proxy_set_header    X-Forwarded-Proto $http_x_forwarded_proto;
          proxy_set_header    Host              $http_host;
          proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
      }
  path: /
```
this installation works well and I'm running upgrade then:

export JOIN_KEY=$(openssl rand -hex 32)

echo ${JOIN_KEY}
7c53fec9edc02fea6f222a19f319e3b7939a26cb82a080802b269ed5344766c3

helm2 upgrade artifactory-tmp --set artifactory.joinKey=${JOIN_KEY} --namespace artifactory-tmp jfrog/artifactory --values artifactory-tmp-new.yml

```
artifactory:
  name: artifactory-tmp
  image:
    registry: docker.bintray.io
    repository: jfrog/artifactory-pro
    pullPolicy: IfNotPresent

  migration:
    enabled: true
    timeoutSeconds: 3600

  license:
    secret: artifactory-license
    dataKey: license

  accessAdmin:
    secret: artifactory-access-admin
    dataKey: bootstrap.creds

  persistence:
    enabled: true
    size: 500Gi
    mountPath: /var/opt/jfrog/artifactory

postgresql:
  enabled: false

database:
  type: postgresql
  driver: org.postgresql.Driver
  secrets:
    url:
      name: artifactory-rds
      key: url
    user:
      name: artifactory-rds
      key: user
    password:
      name: artifactory-rds
      key: password

nginx:
  enabled: false

ingress:
  enabled: true
  hosts:
    - artifactory-tmp.domain.com
  annotations:
    custom.nginx.org/extra-server-names: >-
      ~(?<repo>.+)\.artifactory-tmp.domain.com
    nginx.org/server-snippets: |
      if ($http_x_forwarded_proto = '') {
          set $http_x_forwarded_proto  $scheme;
      }

      rewrite ^/$ /artifactory/webapp/ redirect;
      rewrite ^/artifactory/?(/webapp)?$ /artifactory/webapp/ redirect;
      rewrite ^/(v1|v2)/(.*) /artifactory/api/docker/$repo/$1/$2;

      chunked_transfer_encoding on;
      client_max_body_size 0;

      location /artifactory/ {
          add_header 'Access-Control-Allow-Origin' 'localhost:*';
          add_header 'Access-Control-Allow-Methods' 'GET';
          add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,X-JFrog-Art-Api';
          proxy_read_timeout  2400s;
          proxy_pass_header   Server;
          proxy_cookie_path   ~*^/.* /;
          if ( $request_uri ~ ^/artifactory/(.*)$ ) {
              proxy_pass          http://artifactory-tmp-artifactory-tmp-artifactory--artifactory-tmp-artifactory-8081/artifactory/$1;
          }
          proxy_pass          http://artifactory-tmp-artifactory-tmp-artifactory--artifactory-tmp-artifactory-8081/artifactory/;
          proxy_set_header    X-Forwarded-Port  $server_port;
          proxy_set_header    X-Forwarded-Proto $http_x_forwarded_proto;
          proxy_set_header    Host              $http_host;
          proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
      }
  path: /

```

This command will use latest helm chart and 7.10.5 version of artifactory, I also try to use 7.3.2 version, cause I read here this:
https://www.jfrog.com/confluence/display/JFROG/Upgrading+Artifactory#UpgradingArtifactory-HelmUpgrade

Upgrading from JFrog Artifactory 6.18 or 6.19

If you are using Artifactory version 6.18, you need to upgrade to version 7.3.0 and above.
If you are using Artifactory version 6.19, you need to upgrade to version 7.4.3 and above.

Got the same issue :(

**Comment by skreddy6673** [comment] 2020-11-12 19:14
@lverba Thanks for the additional info, In here they mentioned that master key is mandatory for v7 installs.

https://github.com/jfrog/charts/tree/master/stable/artifactory-ha#create-a-unique-master-key

Try adding the Master key (Old key, this shouldn't be changed) and try the helm upgrade again.

**Comment by lverba** [comment] 2020-11-12 21:01
@skreddy6673 nope, same :(

**Comment by chukka** [comment] 2020-11-16 01:18
@lverba masterKey is not necessary to be passed when you upgrade from 6.x to 7.x (migration takes care of it ). Please refer [here](https://github.com/jfrog/charts/tree/master/stable/artifactory#masterkey-during-6x-to-7x-migration-app-version) for more Info

Please check the length of masterKey used in 6.x for artifactory (32 characters or 64 characters), if you still face an issue - raise a new issue
