### ISSUE TITLE
JFrog XRay Error: Failed to set Postgres statement timeout to 18000000: pq: Invalid Username specified. Please check the Username and retry connection. The Username should be in username@hostname format. After disabling postgres to use external azure posgreql database

### ISSUE THREAD

**Issue by Mugenprime** [jfrog/charts#175] opened 2019-01-11 17:09 UTC
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
 AKS 1.11.5 
HELM v2.12.0 
Azure Database for PostgreSQL server: 10

**Which chart**: jfrog/xray

**What happened**:
[17:25:56 UTC 2019/01/11] [EROR] (jfrog.com/xray/dbaccess.setPostgresStatementTimeoutFromConfig:77) Failed to set Postgres statement timeout to 18000000: pq: Invalid Username specified. Please check the Username and retry connection. The Username should be in username@hostname format.
[17:25:56 UTC 2019/01/11] [EROR] (jfrog.com/xray/migration/db.upgradeDatabasesIfNeeded:84)
[17:25:56 UTC 2019/01/11] [EROR] (jfrog.com/xray/migration/db.upgradeDatabasesIfNeeded:85) Failed to check if migration is needed for postgres. Error: Failed to check postgres migration version: pq: Invalid Username specified. Please check the Username and retry connection. The Username should be in username@hostname format.

Username and password ommitted

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by Mugenprime** [comment] 2019-01-11 17:33
the error message received in the logs when entering the URL with mongodb left as default (enabled) and db url entered is:

Exec: /opt/jfrog/xray-server/server   
[17:25:56 UTC 2019/01/11] [INFO] (jfrog.com/xray/startup.InitXrayServer:67) Xray distribution: docker 
[17:25:56 UTC 2019/01/11] [INFO] (jfrog.com/xray/dbaccess.OpenConnection:36) Setting pq connection username to: xray 
[17:25:56 UTC 2019/01/11] [INFO] (jfrog.com/xray/dbaccess.setPostgresStatementTimeoutFromConfig:74) Setting Postgres statement timeout to 18000000 
[17:25:56 UTC 2019/01/11] [EROR] (jfrog.com/xray/dbaccess.setPostgresStatementTimeoutFromConfig:77) Failed to set Postgres statement timeout to 18000000: pq: Invalid Username specified. Please check the Username and retry connection. The Username should be in <username@hostname> format. 
[17:25:56 UTC 2019/01/11] [EROR] (jfrog.com/xray/migration/db.upgradeDatabasesIfNeeded:84) 
[17:25:56 UTC 2019/01/11] [EROR] (jfrog.com/xray/migration/db.upgradeDatabasesIfNeeded:85) Failed to check if migration is needed for postgres. Error: Failed to check postgres migration version: pq: Invalid Username specified. Please check the Username and retry connection. The Username should be in <username@hostname> format.

when i use the following format for username username@host:password or "Username@host":password

I get the following message:

xray-persist service container is starting... 
Exec: /opt/jfrog/xray-persist/persist   
[17:17:30 UTC 2019/01/11] [EROR] (jfrog.com/xray/dbaccess.OpenConnection:31) Failed to open connection to postgresql DB , bad connection string:bad connection string format: username:password 
[17:17:30 UTC 2019/01/11] [EROR] (jfrog.com/xray/dbaccess.OpenConnection:32)

**Comment by eldada** [comment] 2019-01-11 17:36
@Mugenprime - can you share the custom parameters (or custom values file) which triggered this?

**Comment by Mugenprime** [comment] 2019-01-11 18:32
@eldada The custom values im using are:
helm install --name xray `
             --set common.masterKey=
             --set postgresql.enabled=false `
             --set global.postgresqlUrl=
             --set rabbitmq-ha.enabled=false `
             --set rabbitmq.enabled=true `
             --set ingress.enabled=true `
             --set ingress.hosts[0]=
             --set server.service.type=LoadBalancer `
             --values values-xray.yaml jfrog/xray

**Comment by Mugenprime** [comment] 2019-01-16 10:35
Hi @eldada sorry for the late reply below is the values:

helm install --name xray 
--set common.masterKey=012345678
--set mongodb.enabled=true
--set postgresql.enabled=false 
--set global.postgresqlUrl=postgres://name:password@hostname:port/Database?sslmode=disabled
--set rabbitmq-ha.enabled=false
--set rabbitmq.enabled=true 
--set ingress.enabled=true
--set ingress.hosts[0]="custom hostname"
--set server.service.type=LoadBalancer `
--values values-xray.yaml jfrog/xray

**Comment by eldada** [comment] 2019-01-16 12:12
Try wrapping the value of `global.postgresqlUrl` with quotes.
`--set global.postgresqlUrl='postgres://name:password@hostname:port/Database?sslmode=disabled'`.
Let us know if it helps.

**Comment by Mugenprime** [comment] 2019-01-18 14:51
@eldada will try to test this out over the weekend and let you know.

**Comment by Mugenprime** [comment] 2019-01-18 16:19
Also is there currently any way to change any of the PVC's of the services?

**Comment by eldada** [comment] 2019-01-19 15:58
> @eldada will try to test this out over the weekend and let you know.

Looking forward to hear results.

> Also is there currently any way to change any of the PVC's of the services?

The 4 xray services do not use PVCs. They don't need persistence. As for the others, you'll need to follow each individual chart's docs.

**Comment by Mugenprime** [comment] 2019-01-21 12:09
Hi, 
I've tried wrapping the value in qoutes, but I'm getting the same error message.
If i remember correctly i had this same issue with Artifactorys HELM chart. I was only able to get around it by using the individual variables for the database instead of the URL.
--set database.type=
--set database.host=
--set database.port=
--set database.user=
--set database.password=
Have you been able to test this out on Azure Database for PostgreSQL server?

**Comment by eldada** [comment] 2019-01-21 17:15
For the postgresql error. Can you try and extract the content of the file `/var/opt/jfrog/xray/data/config/xray_config.yaml` from the **xray-server** pod? This file holds the final configuration values.

**Comment by Mugenprime** [comment] 2019-01-22 11:17
Hi I'm unable to do this, because I can't get the container up and running. However when i check the Yaml config for the pod it is pulling the exact connection string i sent you.

**Comment by eldada** [comment] 2019-01-24 08:17
I just noticed there is a mismatch in your examples. You noted `--set mongodb.enabled=false` and later noted `--set mongodb.enabled=true`.
If you set `--set mongodb.enabled=false`, you must also supply `--set global.mongoUrl=${MONGO_URL}`.

As for your postgresql url - it's valid, and using it on my environment works (not Azure). 

Can you check and get back to us?

**Comment by eldada** [comment] 2019-01-24 08:32
I opened #189 to fix missing bit about `mongodb.enabled=false` with external MongoDB.

**Comment by Mugenprime** [comment] 2019-01-24 09:52
Apologies i sent you the wrong config. During my testing I've set this up with MongoDB.enabled=false and MongoDB.enabled=true to try and isolate the issue. However I can assure you I have tried both and many other different configurations and i seem to get the same error message. It would be helpful if you can confirm whether or not you are also experiencing this issue when connecting to Azure PostgreSQL as this may be the cause.

**Comment by suranc** [comment] 2019-04-29 02:50
I am getting a similar error using an externalized postgres, but bundled mongodb.  Here is what I see:

```
xray-analysis service container is starting...
Exec: /opt/jfrog/xray-analysis/analysis
[02:40:44 UTC 2019/04/29] [INFO] (jfrog.com/xray/configs/config/secrets.LoadXraySecretFile:22) Secrets file does not exists
[02:40:44 UTC 2019/04/29] [INFO] (jfrog.com/xray/internal/dbaccess.OpenConnection:36) Setting pq connection username to: xray
[02:40:44 UTC 2019/04/29] [INFO] (jfrog.com/xray/internal/dbaccess.setPostgresStatementTimeoutFromConfig:74) Setting Postgres statement timeout to 18000000
[02:40:44 UTC 2019/04/29] [EROR] (jfrog.com/xray/internal/dbaccess.setPostgresStatementTimeoutFromConfig:77) Failed to set Postgres statement timeout to 18000000: dial tcp: address tcp/keLx8xY: unknown port
```

The value for my db, obfuscated:
```
postgresql:
  enabled: false

global:
  postgresqlUrl: 'postgres://xray:mypassword#@mydbinstance.rds.amazonaws.com:5432/xraydb?sslmode=disable'
```

That's obviously not my password, but it does end in a #.  Could that be interpreted as a special character somewhere along the line?  I would really like to be able to store the host, port, username and password in a secret, and not have to construct a special url and worry about special characters.  I have not tried changing the password, as I do not have the ability to.  But setting it to a deliberately incorrect password gives me an authentication error instead.

**Comment by danielezer** [comment] 2019-04-29 09:28
@Mugenprime @suranc I think you both have the same issue. Looks like @suranc and it is an issue with special characters in the URL. We are looking into this internally but for now I can suggest that you try to use a password without special characters

**Comment by eldada** [comment] 2019-04-29 11:35
This is indeed a bug in Xray. The inability to handle the `#` char in the DB connection string.
Until this is resolved, do not use passwords with `#`. If needed a random password, you can create one with 
```
openssl rand -hex 8
```

**Comment by suranc** [comment] 2019-05-05 18:55
Changing my DB password to one without # in it fixed the issue, so that was indeed the cause of my issue.

**Comment by eldada** [comment] 2019-05-06 04:27
Great! Thanks for the update. FYI - Xray team is working on resolving this bug in one of the coming releases.

**Closed by eldada** 2019-05-06 04:27 UTC

**Comment by cyanfang** [comment] 2020-10-30 05:28
i try to many method to fix this issue, not work. at the last , i found the root cause is my PostgreSQL user password contains special characters.
