### ISSUE TITLE
artifactory fails to connect to postgresql DB

### ISSUE THREAD

**Issue by cmoulliard** [jfrog/charts#1635] opened 2022-06-01 19:13 UTC
**BUG REPORT**

**Version of Helm and Kubernetes**:
k8s: 1.22.9
helm: v3.8.2

**Which chart**:
latest

**What happened**:
```
artifactory fails to connect to the DB
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "artifactory"                                                            ││     at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:646)                                                                  ││     at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:180)                                                                        ││     at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:235)                                                                ││     at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)                                                                                ││     at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223)                                                                                                 ││     at org.postgresql.Driver.makeConnection(Driver.java:400)                                                                                                          ││     at org.postgresql.Driver.connect(Driver.java:259)                                                                                                                 ││     at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)                                                                               ││     at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)                                                                                               ││     at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)                                                                                                ││     at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)                                                                                         ││     at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)                                                                                           ││     at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)                                                                                                  ││     at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)                                                                                    ││     at org.jfrog.storage.wrapper.JFrogDataSourceWrapper.getConnection(JFrogDataSourceWrapper.java:102)                                                                ││     at org.jfrog.storage.wrapper.JFrogDataSourceWrapper.invoke(JFrogDataSourceWrapper.java:71)                                                                        ││     at com.sun.proxy.$Proxy116.getConnection(Unknown Source)                                                                                                          ││     at org.jfrog.access.server.db.util.AccessJdbcHelperImpl.getDbMetadata(AccessJdbcHelperImpl.java:151)                                                              ││     at org.jfrog.access.server.db.util.AccessJdbcHelperImpl.initDb(AccessJdbcHelperImpl.java:143)                                                                     │
│     ... 140 more
```

**What you expected to happen**:
Artifactory pod should be able to connect to the DB

**How to reproduce it** (as minimally and precisely as possible):
```
cat <<EOF > values.yml
artifactory:
  access:
    accessConfig:
      security:
        tls: false
  ingress:
    enabled: true
    hosts:
    - "artifactory.192.168.1.17.nip.io"
  nginx:
    enabled: false
    service:
      type: ClusterIP
  artifactory:
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 5Gi
  postgresql:
    enabled: true
    persistence:
      enabled: true
      size: 5Gi
    postgresqlUsername: artifactory
    postgresqlPassword: artifactory
    postgresqlDatabase: artifactory
EOF

helm install artifactory -f values.yml --create-namespace -n artifactory jfrog/artifactory-oss
```

**Additional information**
Log of the PostgreSQL DB reports:
```
2022-06-01 19:09:51.455 GMT [433] FATAL:  password authentication failed for user "artifactory"
2022-06-01 19:09:51.455 GMT [433] DETAIL:  Password does not match for user "artifactory".
    Connection matched pg_hba.conf line 1: "host     all             all             0.0.0.0/0               md5"
```
This issue seems similar to what I reported top of the backstage helm chart which uses also the bitnami postgresql chart: https://github.com/backstage/backstage/issues/11522
They downgraded the version from 11 to 9 - see: https://github.com/backstage/backstage/blob/master/contrib/chart/backstage/Chart.yaml#L21

**Comment by cmoulliard** [comment] 2022-06-02 04:41
This problem occurs as `helm uninstall` do not remove the PVC and DB is not recreated when we install again the artifactory.

**Comment by eldada** [comment] 2022-06-02 05:00
Helm does not remove the PVC by design. This is to protect you from an accidental remove of your data or state.
A full uninstall requires you to also get the PVCs and delete them with a `kubectl delete pvc ...`.

**Comment by chukka** [comment] 2022-06-10 03:09
Marking this as closed

**Closed by chukka** 2022-06-10 03:09 UTC
