### ISSUE TITLE
[artifactory] Helm Template Error when using artifactory.loggers

### ISSUE THREAD

**Issue by tegataiprime** [jfrog/charts#1791] opened 2023-07-12 20:55 UTC
BUG REPORT

**Version of Helm and Kubernetes**: 
Helm : v3.12.0
K8S: v1.23

**Which chart**:
jfrog/artifactory-ha

**Which product license** (Enterprise/Pro/oss):
Enterprise

**JFrog support reference** (if already raised with support team): 
Case 258264

**What happened**:
Using Chart v107.63.5, the following error message is given by helm...
```
Error: template: artifactory-ha/templates/artifactory-primary-statefulset.yaml:1128:20: executing "artifactory-ha/templates/artifactory-primary-statefulset.yaml" at <.Values.containerSecurityContext.enabled>: can't evaluate field Values in type interface {}
```

**What you expected to happen**:
No error :-P

**How to reproduce it** (as minimally and precisely as possible):
This occurs when additional loggers are defined in the values.yml file:
```
artifactory:
  loggers:
    - artifactory-request.log
```

**Anything else we need to know**:
It looks like this is a scope issue.  The reference to `.Values.containerSecurityContext.enabled` is made inside a `range` block.
Anchoring this reference to the root context should fix it.  e.g.  `$.Values.containerSecurityContext.enabled`

**Comment by kammathavaran** [comment] 2023-07-14 09:47
Looks like a regression issue with the latest version. Will be addressed ASAP.

**Comment by eldada** [comment] 2023-07-15 16:12
I also recommend moving away from the old loggers side-car and use the example we have in
 https://github.com/jfrog/charts/tree/master/examples/artifactory/logging that covers all your logging needs with a single container.

**Comment by tegataiprime** [comment] 2023-07-15 16:17
Thank you.  Good advice.  I am also going to look at moving away from jfrog/artifactory-ha over to jfrog/artifactory.  We're using custom binary file store definitions and custom system settings to work around earlier issues with this chart, which I am sure have all been addressed by now 😄

**Comment by eldada** [comment] 2023-07-16 07:09
It's a good idea to move to artifactory. The artifactory-ha architecture is old and less relevant.

**Comment by tegataiprime** [comment] 2023-07-16 18:12
Ha!  It feels like moving house.  I need to tidy up and pack up my bagage before I move ;)

**Comment by chukka** [comment] 2023-07-21 04:13
@tegataiprime  this issue is fixed internally , will be released in upcoming patch releases (ETA ~ 2 weeks)

**Closed** 2023-07-24 02:06 UTC
