### ISSUE TITLE
Ingress endpoint points to ha-members?

### ISSUE THREAD

**Issue by richmondwang** [jfrog/charts#849] opened 2020-04-24 06:12 UTC
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug (more like a question or clarification)

**Version of Helm and Kubernetes**:
kubernetes

```
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

helm 3.02

**Which chart**:
artifactory-ha 2.4.1

**What happened**:
I enabled ingress

```yml
ingress:
  enabled: true
```

It enable ingress, but the service it is pointing to is to the `releasename-artifactory-ha` service.
Shouldn't it be pointing to the `releasename-artifactory-ha-primary` instead?
https://github.com/jfrog/charts/blob/master/stable/artifactory-ha/templates/ingress.yaml

And when I first enter the license, `primary` takes it and the other members crash (logs below) —leaving the service unable to recover health and get 503 forever. I have to switch the ingress endpoint to point to primary to fix and enter the licenses for the members to consume and recover their health.

```
2020-04-24T05:48:37.670Z [jfrt ] [ERROR] [3c07138834f8157e] [p.HaPropagationServiceImpl:367] [art-exec-7          ] - Error propagating event: tasksList: Unexpected character ('S' (code 83)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: org.apache.http.conn.EofSensorInputStream@7c403e89; line: 1, column: 2]
org.codehaus.jackson.JsonParseException: Unexpected character ('S' (code 83)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: org.apache.http.conn.EofSensorInputStream@7c403e89; line: 1, column: 2]
	at org.codehaus.jackson.JsonParser._constructError(JsonParser.java:1432)
	at org.codehaus.jackson.impl.JsonParserMinimalBase._reportError(JsonParserMinimalBase.java:521)
	at org.codehaus.jackson.impl.JsonParserMinimalBase._reportUnexpectedChar(JsonParserMinimalBase.java:442)
	at org.codehaus.jackson.impl.Utf8StreamParser._handleUnexpectedValue(Utf8StreamParser.java:2090)
	at org.codehaus.jackson.impl.Utf8StreamParser._nextTokenNotInObject(Utf8StreamParser.java:606)
	at org.codehaus.jackson.impl.Utf8StreamParser.nextToken(Utf8StreamParser.java:492)
	at org.codehaus.jackson.map.ObjectMapper._initForReading(ObjectMapper.java:2770)
	at org.codehaus.jackson.map.ObjectMapper._readValue(ObjectMapper.java:2691)
	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1286)
	at org.codehaus.jackson.JsonParser.readValueAs(JsonParser.java:1336)
	at org.artifactory.api.jackson.JacksonReader.streamAsClass(JacksonReader.java:108)
	at org.artifactory.addon.ha.propagate.HaPropagationServiceImpl.propagateResponse(HaPropagationServiceImpl.java:362)
	at org.artifactory.addon.ha.propagate.HaPropagationServiceImpl.lambda$getServerResponse$3(HaPropagationServiceImpl.java:323)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.artifactory.opentracing.TraceableRunnableDecorator.run(TraceableRunnableDecorator.java:30)
	at org.artifactory.concurrent.ArtifactoryRunnable.run(ArtifactoryRunnable.java:53)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**What you expected to happen**:
I expected ingress to point to primary.. (or how should it be?)

**How to reproduce it** (as minimally and precisely as possible):
Just deploy the artifactory-ha chart with ingress enabled.

**Comment by chukka** [comment] 2020-05-04 10:50
@richmondwang  Sorry of the delayed response, by design it points to member nodes only - this is expected, Please refer [here](https://github.com/jfrog/charts/blob/master/stable/artifactory-ha/values.yaml#L1007-L1011). If you want traffic to route to primary also, then set `pool: all`

**Comment by chukka** [comment] 2020-05-04 11:47
I'm marking this as closed, feel free to reopen if you see any issue

**Closed by chukka** 2020-05-04 11:47 UTC
Labels: question
