### ISSUE TITLE
Allow for importing custom CA certificates

### ISSUE THREAD

**Issue by shubb30** [jfrog/charts#617] opened 2020-01-17 19:30 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature request

**Version of Helm and Kubernetes**:
Rancher 2.3.2, Kubernetes 1.15.5

**Which chart**:
Xray

**What happened**:
I deployed Xray in our Kubernetes cluster, and when I tried to point it to my Artifactory instance, it said it could not connect, which I presumed was because of our certificate signed by our corporate CA.

I created a Kubernetes configMap, and added the root and subordinate CA, and then mounted that into the xray-server at /usr/local/share/ca-certificates.  I then logged into the server, and did a `docker exec -it -u root` into the xray server (since the container runs as a non-root user) and then ran the command `update-ca-certificates`, which installs the certificates into the Ubuntu cert store.  This allowed the server to then talk to Artifactory.

The problem is that I would need to run the steps every time the container restarts.

**What you expected to happen**:
Have a Helm chart option for `CA Certificate configMap Name`, which mounts the named CM at the above directory.  Then when the xray-server starts, it needs to run the `update-ca-certificates` command before the server starts so that the certificates get imported.

**Comment by eldada** [comment] 2020-01-18 19:56
Thanks @shubb30 . We'll add this functionality to support mounting a pre-created secret to `/usr/local/share/ca-certificates`. 
Can you confirm mounting to this path solved your connection issue?

**Comment by shubb30** [comment] 2020-01-21 16:16
Thanks @eldada . Mounting that path, and also running `update-ca-certificates` as root fixed the problem.  Running the command would need to be added to the image so that it runs every time the container starts.

**Comment by radekw** [comment] 2020-01-21 21:28
👍

**Comment by eldada** [comment] 2020-01-21 22:08
As noted - we are running as non-root, so running `update-ca-certificates` might be an issue. We'll look into the possible options here.

**Comment by eldada** [comment] 2020-01-25 18:04
Update: We are checking the possibility to add support for this in the Xray application itself as the non-root issue is critical.

**Comment by jshrack-ssi** [comment] 2020-02-11 15:54
We too are running into this same issue. Our Artifactory instance is running with a certificate with an untrusted intermediate certificate which needs to be added to the trust chain. The only other alternative is to use an insecure link to Artifactory which is breaks SSO. Adding this feature to the XRay chart would be greatly appreciated.

**Comment by evannorstrand** [comment] 2020-04-24 15:42
Duplicate of #759 

@chukka fix the code the code broken in the PR and CA Certs will once again work :)

**Comment by chukka** [comment] 2020-07-21 12:12
@shubb30  is this still an issue ? can you please confirm which version of xray you are using ? if you are using Unified (xray 3.x), please refer [here](https://github.com/jfrog/charts/blob/master/stable/xray/README.md#establishing-tls-and-adding-certificates)

I'm marking this issue as closed

**Closed by chukka** 2020-07-21 12:12 UTC
Labels: duplicate, question
