### ISSUE TITLE
GCS buckets integration via service account

### ISSUE THREAD

**Issue by satyamag** [jfrog/charts#304] opened 2019-04-11 11:08 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE

Use service accounts to natively integrate google storage buckets.

For using google storage buckets as the binary store the current approach requires the use of the interoperability API which is meant as a means to migrate from AWS. Since it needs to be enabled per user it is not a great solution for ensuring high levels of service reliability incase there are any issues with that users account or they leave the organisation. For a capability as critical as artifact storage it becomes imperative that the integration be enabled using a service account that is independent of an individual.

**Comment by jainishshah17** [comment] 2019-04-12 18:22
@satyamag Looks like you will have to create FEATURE REQUEST for this in Artifactory. (Jira)[https://www.jfrog.com/jira/]

**Comment by eldada** [comment] 2019-04-15 17:00
@satyamag We already have this feature in development. Hope it's released in one of the coming Artifactory versions. Once released, we'll add it to the helm chart.

**Comment by satyamag** [comment] 2019-04-16 00:46
Thanks folks. Great to hear its coming soon. Cheers!

**Comment by lexual** [comment] 2019-07-04 03:51
Hi @eldada . Any updates on this feature going public anytime soon?

**Comment by eldada** [comment] 2019-07-04 04:27
Sorry @lexual and @satyamag . Still not estimation...

**Comment by jdamour98** [comment] 2020-03-02 06:43
@eldada Pinging. Any update? Can you link the Jira issue here?

**Comment by eldada** [comment] 2020-03-07 16:03
Hi. Sorry. No estimate. There is an internal issue. Care to open a new, public JIRA and share it here? Also welcome to vote for it. I will link it internally.

**Comment by jdamour98** [comment] 2020-03-09 16:09
I've tried to create it twice now and I keep getting 
```
Error
[object Object]
```
Can you please create it? Here are the details:

Current: Artifactory uses identity/credential (access token) to authorize GCS
Expected: Artifactory should use service account keys like any other application.

**Comment by jdamour98** [comment] 2020-03-09 16:12
Ok well apparenly it was created successfully. The UI certainly didn't indicate that. The issue is `RTFACT-21493`, please link it internally @eldada

**Comment by eldada** [comment] 2020-03-09 19:55
Thx @jdamour98 . I made the link and will try to push this internally further.

**Comment by eldada** [comment] 2020-03-10 12:34
Update: Seems this feature is almost ready and will be announced in one of the coming releases. We will also add support for it in our Artifactory HA chart.

**Comment by jdamour98** [comment] 2020-03-10 16:53
Awesome!! Thanks so much for keeping us posted @eldada, can't wait for it!

**Comment by eldada** [comment] 2020-03-23 10:46
Great new! https://github.com/jfrog/charts/pull/696 has the new feature. Take it for a spin and let us know... Artifactory HA chart version `2.0.36`

**Closed by eldada** 2020-03-23 10:46 UTC

**Comment by jdamour98** [comment] 2020-06-11 18:39
@eldada FYI opened #940 to copy to [artifactory] chart, where i need it.
